driver:
  name: vagrant

provisioner:
  name: chef_solo
  cookbooks_path:
    - ../components/cookbooks

platforms:
- name: centos-7.1
  
suites:
  - name: default
    run_list:
      - recipe[tomcat-8.5::add]
